apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: ocp-96vs5-worker-guardrails-us-east-2a
  namespace: openshift-machine-api
spec:
  minReplicas: 0
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: ocp-96vs5-worker-guardrails-us-east-2a
